apiVersion: v1
kind: Service
metadata:
  name: nuqta-service
  namespace: Blood-donation-prod
  labels:
    app: nuqta-app

spec:
  type: LoadBalancer
  selector:
    app: nuqta-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
