name: Release (Create Docker Image and Push in Docker Hub)

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    env:
      DOCKER_REPO: ramyavalliv/blood-donation-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.PROD_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.PROD_DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and Tag Docker Image
        run: |
          version=${GITHUB_REF#refs/tags/}
          echo "Using version: $version"

          docker build -t $DOCKER_REPO:$version .

      - name: Push Docker Image
        run: |
          version=${GITHUB_REF##*/}
          echo "Using version: $version"

          docker push $DOCKER_REPO:$version

          echo "\`docker run -p 3000:3000 $DOCKER_REPO:$version\`" > release.txt
